
#include "brm.h"

struct MachineFieldMoves gFieldMoves[] = {
    {BRMPrepareFlash, BRMLaunchExitOverworld, FlashErrorMsg},
    {BRMPrepareCut, BRMLaunchExitOverworld, CutErrorMsg},
	{BRMPrepareFly, BRMLaunchFly, FlyErrorMsg},
	{BRMPrepareStrength, BRMLaunchExitOverworld, StrengthErrorMsg},
	{BRMPrepareSurf, BRMLaunchExitOverworld, SurfErrorMsg},
	{BRMPrepareRockSmash, BRMLaunchExitOverworld, RockSmashErrorMsg},
	{BRMPrepareWaterfall, BRMLaunchExitOverworld, WaterfallErrorMsg},
	{BRMPrepareTeleport, BRMLaunchTeleport, TeleportErrorMsg},
	{BRMPrepareDig, BRMLaunchDig, DigErrorMsg},
	{BRMPrepareSoftboiledAndMilkDrink, BRMLaunchSoftboiledAndMilkDrink, MilkDrinkErrorMsg},
	{BRMPrepareSoftboiledAndMilkDrink, BRMLaunchSoftboiledAndMilkDrink, MilkDrinkErrorMsg},
	{BRMPrepareSweetScent, BRMLaunchExitOverworld, SweetScentErrorMsg},
	{BRMPrepareDive, BRMLaunchExitOverworld, DiveErrorMsg},
};

struct MachineBRM gBrmLauncher[] = {
	{summaryString, brmLaunchSummary},
	{switchString, brmLaunchSwitch},
	{cancelString, brmLaunchCancel},
	{itemString, brmLaunchItemMenu},
	{giveString, brmLaunchGiveItem},
	{takeString, brmLaunchTakeItem},
	{mailString, brmLaunchMailMenu},
	{takeString, brmLaunchTakeMail},
	{readString, brmLaunchReadMail},
	{cancelString, brmLaunchCancelSubBrmMenu},
	{shiftString, brmLaunchShiftOrSendOut},
	{sendOutString, brmLaunchShiftOrSendOut},
	{enterString, brmLaunchEnter},
	{noEntryString, brmLaunchNoEntry},
	{storeString, brmLaunchStore},
	{registerString, brmLaunchRegister},
	{tradeString, brmLaunchTrade},
	{tradeString, brmLaunchNull},
	{flashString, ValidateAndLaunchFieldmove},
	{cutString, ValidateAndLaunchFieldmove},
	{flyString, ValidateAndLaunchFieldmove},
	{strengthString, ValidateAndLaunchFieldmove},
	{surfString, ValidateAndLaunchFieldmove},
	{rockSmashString, ValidateAndLaunchFieldmove},
	{waterfallString, ValidateAndLaunchFieldmove},
	{teleportString, ValidateAndLaunchFieldmove},
	{digString, ValidateAndLaunchFieldmove},
	{milkDrinkString, ValidateAndLaunchFieldmove},
	{softboiledString, ValidateAndLaunchFieldmove},
	{sweetScentString, ValidateAndLaunchFieldmove},
	{diveString, ValidateAndLaunchFieldmove},
};


u16 fieldMoveIdTable[] = {
	MOVE_FLASH,
	MOVE_CUT,
	MOVE_FLY,
	MOVE_STRENGTH,
	MOVE_SURF,
	MOVE_ROCKSMASH,
	MOVE_WATERFALL,
	MOVE_TELEPORT,
	MOVE_DIG,
	MOVE_MILKDRINK,
	MOVE_SOFTBOILED,
	MOVE_SWEETSCENT,
	MOVE_DIVE,
	moveIdTerminator,
};

u32 gHmHelper[] = {
	&summaryDescription,
	&switchDescription,
	&cancelDescription,
	&itemDescription,
	&giveItemDescription,
	&takeItemDescription,
	&mailDescription,
	&takeMailDescription,
	&readMailDescription,
	&cancelSubMenuDescription,
	&shiftDescription,
	&sendOutDescription,
	&enterDescription,
	&noEntryDescription,
	&storeDescription,
	&registerDescription,
	&tradeDescription,
	&nullDescription,
	&flashDescription,
	&cutDescription,
	&flyDescription,
	&strengthDescription,
	&surfDescription,
	&rockSmashDescription,
	&waterfallDescription,
	&teleportDescription,
	&digDescription,
	&milkDrinkDescription,
	&softboiledDescription,
	&sweetScentDescription,
	&diveDescription,
};

