#include <pokeagb/pokeagb.h>
#include "evolution_table.h"
#include "../pokemon.h"

const struct Evolution gEvolutionTable[SPECIES_MAX][EVOS_PER_MON] =
{
    //HORSEA
    {{EVO_LEVEL, 32, SPECIES_SEADRA, 0}},

    //SEADRA
    {{EVO_TRADE_ITEM, ITEM_DRAGONSCALE, SPECIES_KINGDRA, 0}},

    //KINGDRA
    {},

    //TRAPINCH
    {{EVO_LEVEL, 35, SPECIES_VIBRAVA, 0}},

    //VIBRAVA
    {{EVO_LEVEL, 45, SPECIES_FLYGON, 0}},

    //FLYGON
    {},

    //TOGEPI
    {{EVO_FRIENDSHIP, 0, SPECIES_TOGETIC, 0}},

    //TOGETIC
    {{EVO_ITEM, 0, SPECIES_TOGETIC, 0}},

    //TOGEKISS
    {},

    //YOUNGOOS
    {{EVO_LEVEL_DAY, 20, SPECIES_GUMSHOOS, 0}},

    //GUMSHOOS
    {},

    //BUNNELBY
    {{EVO_LEVEL, 20, SPECIES_DIGGERSBY, 0}},

    //DIGGERSBY
    {},

    //BOUNSWEET
    {{EVO_LEVEL, 18, SPECIES_STEENEE, 0}},

    //STEENEE
    {{EVO_LEVEL_KNOW_MOVE, 0, SPECIES_TSAREENA, MOVE_STOMP}},

    //TSAREENA
    {},

    //MAREEP
    {{EVO_LEVEL, 15, SPECIES_FLAAFFY, 0}},

    //FLAAFFY
    {{EVO_LEVEL, 30, SPECIES_AMPHAROS, 0}},

    //AMPHAROS
    {},

    //COMBEE
    {{EVO_LEVEL_GENDER, 21, SPECIES_VESPIQUEN, 0}},

    //VESPIQUEN
    {},

    //SPINARAK
    {{EVO_LEVEL, 22, SPECIES_ARIADOS, 0}},

    //ARIADOS
    {},

    //JOLTIK
    {{EVO_LEVEL, 36, SPECIES_GALVANTULA, 0}},

    //GALVANTULA
    {},

    //DEWPIDER
    {{EVO_LEVEL, 36, SPECIES_GALVANTULA, 0}},

    //ARAQUANID
    {},

    //ZUBAT
    {{EVO_LEVEL, 22, SPECIES_GOLBAT, 0}},

    //GOLBAT
    {{EVO_FRIENDSHIP, 0, SPECIES_CROBAT, 0}},

    //CROBAT
    {},

    //YANMA
    {{EVO_LEVEL_KNOW_MOVE, 0, SPECIES_YANMEGA, MOVE_ANCIENTPOWER}},

    //MORELULL
    {{EVO_LEVEL, 24, SPECIES_SHIINOTIC, 0}},

    //SPECIES_SHIINOTIC
    {},

    //VULPIX
    {{EVO_ITEM, ITEM_FIRESTONE, SPECIES_NINETALES, 0}},

    //NINETALES
    {},

    //GROWLITHE
    {{EVO_ITEM, ITEM_FIRESTONE, SPECIES_ARCANINE, 0}},

    //ARCANINE
    {},

    //PINECO
    {{EVO_LEVEL,31,SPECIES_FORRETRESS, 0}},

    //FORRETRESS
    {},

    //NINCADA
    {{EVO_LEVEL_NINJASK,20,SPECIES_NINJASK, 0},
    {EVO_LEVEL_SHEDINJA,20,SPECIES_SHEDINJA, 0}},

    //NINJASK
    {},

    //SHEDINJA
    {},

    //FEEBAS
    {{EVO_BEAUTY, 170, SPECIES_MILOTIC, 0},
    {EVO_TRADE_ITEM, 0, SPECIES_MILOTIC, 0}},

    //MILOTIC
    {},

    //SHELLDER
    {{EVO_ITEM, ITEM_WATERSTONE, SPECIES_CLOYSTER, 0}},

    //CLOYSTER
    {},

    //SLOWPOKE
    {{EVO_LEVEL, 37, SPECIES_SLOWBRO, 0},
    {EVO_TRADE_ITEM, ITEM_KINGSROCK, SPECIES_SLOWKING, 0}},

    //SLOWBRO
    {},

    //SLOWKING
    {},

    //ABRA
    {{EVO_LEVEL, 16, SPECIES_KADABRA, 0}},

    //KADABRA
    {{EVO_TRADE, 0, SPECIES_ALAKAZAM, 0}},

    //ALAKAZAM
    {},

    //ESPURR
    {{EVO_LEVEL, 25, SPECIES_MEOWSTIC, 0}},

    //MEOWSTIC
    {},

    //COTTONEE
    {{EVO_ITEM, ITEM_SUNSTONE, SPECIES_WHIMSICOTT, 0}},

    //WHIMSICOTT
    {},

    //PETILIL
    {{EVO_ITEM, ITEM_SUNSTONE, SPECIES_LILLIGANT, 0}},

    //SHROOMISH
    {{EVO_LEVEL, 23, SPECIES_BRELOOM, 0}},

    //BRELOOM
    {},

    //SWABLU
    {{EVO_LEVEL, 35, SPECIES_ALTARIA, 0}},

    //ALTARIA
    {},

    //MURKROW
    {{EVO_ITEM, 0, SPECIES_HONCHKROW, 0}},

    //HONCHKROW
    {},

    //CLEFFA
    {{EVO_FRIENDSHIP, 0 , SPECIES_CLEFAIRY, 0}},

    //CLEFAIRY
    {{EVO_ITEM, ITEM_MOONSTONE, SPECIES_CLEFABLE, 0}},

    // CLEFABLE
    {},

    //RIOLU
    {{EVO_FRIENDSHIP, 0, SPECIES_LUCARIO, 0}},

    //LUCARIO
    {},

    //MACHOP
    {{EVO_LEVEL, 28, SPECIES_MACHOKE, 0}},

    //MACHOKE
    {{EVO_TRADE, 0, SPECIES_MACHAMP, 0}},

    //MACHAMP
    {},

    //SHINX
    {{EVO_LEVEL, 15, SPECIES_LUXIO, 0}},

    //LUXIO
    {{EVO_LEVEL, 30, SPECIES_LUXRAY, 0}},

    //LUXRAY
    {},

    //LITLEO
    {{EVO_LEVEL, 35, SPECIES_PYROAR, 0}},

    //PYROAR
    {},

    //HOUNDOUR
    {{EVO_LEVEL, 24, SPECIES_HOUNDOOM, 0}},

    //HOUNDOOM
    {},

    //WINGULL
    {{EVO_LEVEL, 25, SPECIES_PELIPPER, 0}},

    //PELIPPER
    {},

    //TENTACOOL
    {{EVO_LEVEL, 30, SPECIES_TENTACRUEL, 0}},

    //TENTACRUEL
    {},

    //REMORAID
    {{EVO_LEVEL, 25, SPECIES_OCTILLERY, 0}},

    //OCTILLERY
    {},

    //INKAY
    {{EVO_LEVEL, 30, SPECIES_MALAMAR, 0}},

    //MALAMAR
    {},

    //DWEBBLE
    {{EVO_LEVEL, 34, SPECIES_CRUSTLE, 0}},

    //CRUSTLE
    {},

    //SKRELP
    {{EVO_LEVEL, 48, SPECIES_DRAGALGE, 0}},

    //DRAGALGE
    {},

    //TRUBBISH
    {{EVO_LEVEL, 36, SPECIES_GARBODOR, 0}},

    //GARBODOR
    {},

    //CROAGUNK
    {{EVO_LEVEL, 37, SPECIES_TOXICROAK, 0}},

    //TOXICROAK
    {},

    //SKORUPI
    {{EVO_LEVEL, 40, SPECIES_DRAPION, 0}},

    //DRAPION
    {},

    //CARNIVINE
    {},

    //GOOMY
    {{EVO_LEVEL, 40, SPECIES_SLIGGOO, 0}},

    //SLIGGOO
    {{EVO_LEVEL_WEATHER, 50, SPECIES_GOODRA, 0}},

    //GOODRA
    {},

    //MUDBRAY
    {{EVO_LEVEL, 30, SPECIES_MUDSDALE, 0}},

    //MUDSDALE
    {},

    //GASTLY
    {{EVO_LEVEL, 25, SPECIES_HAUNTER, 0}},

    //HAUNTER
    {{EVO_TRADE, 0, SPECIES_GENGAR, 0}},

    //GENGAR
    {},

    //DUSKULL
    {{EVO_LEVEL, 37, SPECIES_DUSCLOPS, 0}},

    //DUSCLOPS
    {{EVO_TRADE_ITEM, 0, SPECIES_DUSKNOIR, 0}},

    //DUSKNOIR
    {},

    //NOIBAT
    {{EVO_LEVEL, 48, SPECIES_NOIVERN, 0}},

    //NOIVERN
    {},

    //DUNSPARCE
    {},

    //MIENFOO
    {{EVO_LEVEL, 50, SPECIES_MIENSHAO, 0}},

    //MIENSHAO
    {},

    //BLITZLE
    {{EVO_LEVEL, 27, SPECIES_ZEBSTRIKA, 0}},

    //ZEBSTRIKA
    {},

    //PONYTA
    {{EVO_LEVEL, 40, SPECIES_RAPIDASH, 0}},

    //RAPIDASH
    {},

    //HERACROSS
    {},

    //SCYTHER
    {{EVO_TRADE_ITEM, ITEM_METALCOAT, SPECIES_SCIZOR, 0}},

    //SCIZOR
    {},

    //EEVEE
    {{EVO_ITEM, ITEM_THUNDERSTONE, SPECIES_JOLTEON, 0},
    {EVO_ITEM, ITEM_WATERSTONE, SPECIES_VAPOREON, 0},
    {EVO_ITEM, ITEM_FIRESTONE, SPECIES_FLAREON, 0},
    {EVO_ITEM, ITEM_FIRESTONE, SPECIES_FLAREON, 0},
    {EVO_LEVEL_EEVEE, 0, SPECIES_GLACEON, 0}},
    /*
    {EVO_NEAR_MOSS, 0, SPECIES_GLACEON, 0},
    {EVO_NEAR_ICE, 0, SPECIES_LEAFEON, 0},
    {EVO_LEVEL_MOVE_TYPE, 0, SPECIES_SYLVEON, 0},
    {EVO_FRIENDSHIP_DAY, 0, SPECIES_ESPEON, 0},
    {EVO_FRIENDSHIP_NIGHT, 0, SPECIES_UMBREON, 0}},
    */

    //ROCKRUFF
    {{EVO_LEVEL_DAY, 25, SPECIES_LYCANROC, 0},
    {EVO_LEVEL_NIGHT, 25, SPECIES_LYCANROC, 0},
    {EVO_LEVEL_DUSK, 25, SPECIES_LYCANROC, 0}},

    //LYCANROC
    {},

    //GEODUDE
    {{EVO_LEVEL, 25, SPECIES_GRAVELER, 0}},

    //GRAVELER
    {{EVO_TRADE, 0, SPECIES_GOLEM, 0}},

    //GOLEM
    {},

    //ANORITH
    {{EVO_LEVEL, 40, SPECIES_ARMALDO, 0}},

    //ARMALDO
    {},

    //LILEEP
    {{EVO_LEVEL, 40, SPECIES_CRADILY, 0}},

    //CRADILY
    {},

    //CHINCHOU
    {{EVO_LEVEL, 27, SPECIES_LANTURN, 0}},

    //LANTURN
    {},

    //STARYU
    {{EVO_ITEM, ITEM_WATERSTONE, SPECIES_STARMIE, 0}},

    //STARMIE
    {},

    //SPHEAL
    {{EVO_LEVEL, 32, SPECIES_SEALEO, 0}},

    //SEALEO
    {{EVO_LEVEL, 44, SPECIES_WALREIN, 0}},

    //WALREIN
    {},

    //PAWNIARD
    {{EVO_LEVEL, 52, SPECIES_BISHARP, 0}},

    //BISHARP
    {},

    //SCRAGGY
    {{EVO_LEVEL, 39, SPECIES_SCRAFTY, 0}},

    //SCRAFTY
    {},

    //GLIGAR
    {{EVO_LEVEL_ITEM_NIGHT, 39, SPECIES_GLISCOR, 0}},

    //GLISCOR
    {},

    //SKIDDO
    {{EVO_LEVEL, 32, SPECIES_GOGOAT, 0}},

    //GOGOAT
    {},

    //DRAMPA
    {},

    //LARVITAR
    {{EVO_LEVEL, 30, SPECIES_PUPITAR, 0}},

    //PUPITAR
    {{EVO_LEVEL, 55, SPECIES_TYRANITAR, 0}},

    //TYRANITAR
    {},

    //SALANDIT
    {{EVO_LEVEL_GENDER, 33, SPECIES_SALAZZLE, EVO_REQ_FEMALE}},

    //SALAZZLE
    {},

    //SANDILE
    {{EVO_LEVEL, 29, SPECIES_KROKOROK, 0}},

    //KROKOROK
    {{EVO_LEVEL, 40, SPECIES_KROOKODILE, 0}},

    //KROOKODILE
    {},

    //SIGILYPH
    {},

    //MARACTUS
    {},

    //CACNEA
    {{EVO_LEVEL, 32, SPECIES_CACTURNE, 0}},

    //CACTURNE
    {},

    //SHUCKLE
    {},

    //SLUGMA
    {{EVO_LEVEL, 38, SPECIES_MAGCARGO, 0}},

    //MAGCARGO
    {},

    //TORKOAL
    {},

    //TURTONATOR
    {},

    //LARVESTA
    {{EVO_LEVEL, 59, SPECIES_VOLCARONA, 0}},

    //VOLCARONA
    {},

    //SWIRLIX
    {{EVO_TRADE_ITEM, 0, SPECIES_SLURPUFF, 0}},

    //SLURPUFF
    {},

    //SNUBBULL
    {{EVO_LEVEL, 23, SPECIES_GRANBULL}},

    //GRANBULL
    {},

    //TYNAMO
    {{EVO_LEVEL, 39, SPECIES_EELEKTRIK, 0}},

    //EELEKTRIK
    {{EVO_ITEM, ITEM_THUNDERSTONE, SPECIES_EELEKTROSS, 0}},

    //EELEKTROSS
    {},

    //MAGNEMITE
    {{EVO_LEVEL, 30, SPECIES_MAGNETON, 0}},

    //MAGNETON
    {{EVO_LEVEL_ELEC_FIELD, 0, SPECIES_MAGNEZONE, 0}},

    //MAGNEZONE
    {},

    //TOGEDEMARU
    {},

    //ROTOM
    {},

    //SANDYGAST
    {{EVO_LEVEL, 42, SPECIES_PALOSSAND, 0}},

    //PALOSSAND
    {},

    //LITWICK
    {{EVO_LEVEL, 41, SPECIES_LAMPENT, 0}},

    //LAMPENT
    {{EVO_ITEM, 0, SPECIES_CHANDELURE, 0}},

    //CHANDELURE
    {},

    //DHELMISE
    {},

    //HONEDGE
    {{EVO_LEVEL, 35, SPECIES_DOUBLADE, 0}},

    //DOUBLADE
    {{EVO_ITEM, 0, SPECIES_AEGISLASH, 0}},

    //AEGISLASH
    {},

    //SPIRITOMB
    {},

    //MAWILE
    {},

    //GIRAFARIG
    {},

    //MUNCHLAX
    {{EVO_FRIENDSHIP, 0, SPECIES_SNORLAX, 0}},

    //SNORLAX
    {},

    //PANCHAM
    {{EVO_LEVEL_WITH_TYPE, 32, SPECIES_PANGORO, TYPE_DARK}},

    //PANGORO
    {},

    //PASSIMIAN
    {},

    //STUFFUL
    {{EVO_LEVEL, 27, SPECIES_BEWEAR, 0}},

    //BEWEAR
    {},

    //BOUFFALANT
    {},

    //KANGASKHAN
    {},

    //HAWLUCHA
    {},

    //TROPIUS
    {},

    //LAPRAS
    {},

    //SKARMORY
    {},

    //SNEASEL
    {{EVO_LEVEL_ITEM_NIGHT, 0, SPECIES_WEAVILE, 0}},

    //WEAVILE
    {},

    //SNOVER
    {{EVO_LEVEL, 40, SPECIES_ABOMASNOW, 0}},

    //ABOMASNOW
    {},

    //SNORUNT
    {{EVO_LEVEL, 42, SPECIES_GLALIE, 0},
    {EVO_ITEM, 0, SPECIES_FROSLASS, 0}},

    //GLALIE
    {},

    //FROSLASS
    {},

    //BERMITE
    {{EVO_LEVEL, 37, SPECIES_AVALUGG, 0}},

    //CRYOGONAL
    {},

    //PORYGON
    {{EVO_TRADE_ITEM, ITEM_UPGRADE, SPECIES_PORYGON2, 0}},

    //PORYGON2
    {{EVO_TRADE_ITEM, 0, SPECIES_PORYGONZ, 0}},

    //PORYGONZ
    {},

    //DRUDDIGON
    {},

    //GOLETT
    {{EVO_LEVEL, 43, SPECIES_GOLURK, 0}},

    //GOLURK
    {},

    //DRILBUR
    {{EVO_LEVEL, 31, SPECIES_EXCADRILL, 0}},

    //EXCADRILL
    {},

    //BELDUM
    {{EVO_LEVEL, 20, SPECIES_METANG, 0}},

    //METANG
    {{EVO_LEVEL, 45, SPECIES_METAGROSS, 0}},

    //METAGROSS
    {},

    //GIBLE
    {{EVO_LEVEL, 24, SPECIES_GABITE, 0}},

    //GABITE
    {{EVO_LEVEL, 48, SPECIES_GARCHOMP, 0}},

    //GARCHOMP
    {},

    //DRATINI
    {{EVO_LEVEL, 30, SPECIES_DRAGONAIR, 0}},

    //DRAGONAIR
    {{EVO_LEVEL, 55, SPECIES_DRAGONITE, 0}},

    //DRAGONITE
    {},

    //LATIAS
    {},

    //LATIOS
    {},

    //HEATRAN
    {},

    //DEOXYS
    {},

    //JIRACHI
    {},

    //DARKRAI
    {},

};
