#include "brm.h"

struct MachineFieldMoves gFieldMoves[] = {
    {BRMPrepareFlash, BRMLaunchExitOverworld, FlashErrorMsg},
    {BRMPrepareCut, BRMLaunchExitOverworld, CutErrorMsg},
	{BRMPrepareFly, BRMLaunchFly, FlyErrorMsg},
	{BRMPrepareStrength, BRMLaunchExitOverworld, StrengthErrorMsg},
	{BRMPrepareSurf, BRMLaunchExitOverworld, SurfErrorMsg},
	{BRMPrepareRockSmash, BRMLaunchExitOverworld, RockSmashErrorMsg},
	{BRMPrepareWaterfall, BRMLaunchExitOverworld, WaterfallErrorMsg},
	{BRMPrepareTeleport, BRMLaunchTeleport, TeleportErrorMsg},
	{BRMPrepareDig, BRMLaunchDig, DigErrorMsg},
	{BRMPrepareSoftboiledAndMilkDrink, BRMLaunchSoftboiledAndMilkDrink, MilkDrinkErrorMsg},
	{BRMPrepareSoftboiledAndMilkDrink, BRMLaunchSoftboiledAndMilkDrink, MilkDrinkErrorMsg},
	{BRMPrepareSweetScent, BRMLaunchExitOverworld, SweetScentErrorMsg},
	{BRMPrepareDive, BRMLaunchExitOverworld, DiveErrorMsg},
};

struct MachineBRM gBrmLauncher[] = {
	{summaryString, BRMLaunchSummary},
	{switchString, BRMLaunchSwitch},
	{cancelString, BRMLaunchCancel},
	{itemString, BRMLaunchItemMenu},
	{giveString, BRMLaunchGiveItem},
	{takeString, BRMLaunchTakeItem},
	{mailString, BRMLaunchMailMenu},
	{takeString, BRMLaunchTakeMail},
	{readString, BRMLaunchReadMail},
	{cancelString, BRMLaunchCancelSubBrmMenu},
	{shiftString, BRMLaunchShiftOrSendOut},
	{sendOutString, BRMLaunchShiftOrSendOut},
	{enterString, BRMLaunchEnter},
	{noEntryString, BRMLaunchNoEntry},
	{storeString, BRMLaunchStore},
	{registerString, BRMLaunchRegister},
	{tradeString, BRMLaunchTrade},
	{tradeString, BRMLaunchNull},
	{flashString, ValidateAndLaunchFieldmove},
	{cutString, ValidateAndLaunchFieldmove},
	{flyString, ValidateAndLaunchFieldmove},
	{strengthString, ValidateAndLaunchFieldmove},
	{surfString, ValidateAndLaunchFieldmove},
	{rockSmashString, ValidateAndLaunchFieldmove},
	{waterfallString, ValidateAndLaunchFieldmove},
	{teleportString, ValidateAndLaunchFieldmove},
	{digString, ValidateAndLaunchFieldmove},
	{milkDrinkString, ValidateAndLaunchFieldmove},
	{softboiledString, ValidateAndLaunchFieldmove},
	{sweetScentString, ValidateAndLaunchFieldmove},
	{diveString, ValidateAndLaunchFieldmove},
};


u16 fieldMoveIdTable[] = {
	MOVE_FLASH,
	MOVE_CUT,
	MOVE_FLY,
	MOVE_STRENGTH,
	MOVE_SURF,
	MOVE_ROCKSMASH,
	MOVE_WATERFALL,
	MOVE_TELEPORT,
	MOVE_DIG,
	MOVE_MILKDRINK,
	MOVE_SOFTBOILED,
	MOVE_SWEETSCENT,
	MOVE_DIVE,
	0xFFFF,
};

const pchar* gHmHelper[] = {
	summaryDescription,
	switchDescription,
	cancelDescription,
	itemDescription,
	giveItemDescription,
	takeItemDescription,
	mailDescription,
	takeMailDescription,
	readMailDescription,
	cancelSubMenuDescription,
	shiftDescription,
	sendOutDescription,
	enterDescription,
	noEntryDescription,
	storeDescription,
	registerDescription,
	tradeDescription,
	nullDescription,
	flashDescription,
	cutDescription,
	flyDescription,
	strengthDescription,
	surfDescription,
	rockSmashDescription,
	waterfallDescription,
	teleportDescription,
	digDescription,
	milkDrinkDescription,
	softboiledDescription,
	sweetScentDescription,
	diveDescription,
};
