#ifndef MOVE_DATA_H_
#define MOVE_DATA_H_

#include <pokeagb/pokeagb.h>
#include "moves.h"
#include "../anonymous_callbacks/anonymous_callbacks.h"


/* Move callback funcs */
extern void payday_ondmg(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 ohko_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 solarbeam_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 solarblade_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 freeze_shock_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 ice_burn_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 razor_wind_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 sky_attack_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 fly_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 bounce_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 gust_on_invul_hit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void acrobatics_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 partially_trapped_effect_cb(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 minimize_on_effect_cb(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 stomp_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 jump_kick_on_move_fail(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 bodyslam_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 thrash_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 thrash_on_move_fail(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void thrash_on_after_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void sonic_boom_on_dmg(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 disable_on_effect_cb(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 rollout_on_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 rollout_on_move_fail(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void rollout_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 metronome_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 mirror_move_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 sleep_talk_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 sleep_talk_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 assist_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 copycat_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 clear_smog_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 magic_coat_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 me_first_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 snatch_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 conversion_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 conversion_two_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 reflect_type_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 soak_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 flying_press_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void flying_press_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 trick_or_treat_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 rest_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 ion_deluge_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 electrify_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 electrify_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void psywave_on_damage_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 burn_up_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 burn_up_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 protect_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 protection_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void seismic_toss_on_damage_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 cotton_spore_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void endure_on_damage(u8 user, u8 source, u16 move, struct anonymous_callback* acb);
extern u8 endure_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 wide_guard_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 mat_block_on_tryhit(u8 user, u8 source, u16 move, struct anonymous_callback* acb);
extern u8 mat_block_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 crafty_shield_on_tryhit(u8 user, u8 source, u16 move, struct anonymous_callback* acb);
extern u8 crafty_shield_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 feint_on_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 hyperspace_hole_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 shadow_force_on_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 phantom_force_on_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 present_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 reflect_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 light_screen_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 aurora_veil_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 aurora_veil_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 rain_dance_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 sunny_day_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 hail_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 sandstorm_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 brickbreak_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 future_sight_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 wish_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 yawn_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 yawn_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 charge_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 doom_desire_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void counter_before_turn(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 counter_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 mirror_coat_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void mirror_coat_before_turn(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 metal_burst_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void metal_burst_before_turn(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 hurricane_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 hurricane_on_tryhit_inv(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 weather_ball_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 electric_terrain_on_effect(u8 bank, u8 src, u16 stat_id, struct anonymous_callback* acb);
extern u8 grassy_terrain_on_effect(u8 bank, u8 src, u16 stat_id, struct anonymous_callback* acb);
extern u8 misty_terrain_on_effect(u8 bank, u8 src, u16 stat_id, struct anonymous_callback* acb);
extern u8 psychic_terrain_on_effect(u8 bank, u8 src, u16 stat_id, struct anonymous_callback* acb);
extern u8 secret_power_on_modify(u8 bank, u8 src, u16 stat_id, struct anonymous_callback* acb);
extern u8 floral_healing_on_modify(u8 bank, u8 src, u16 stat_id, struct anonymous_callback* acb);
extern u8 camouflage_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 nature_power_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void water_spout_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void stored_power_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void punishment_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 hidden_power_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 revelation_dance_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void hex_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void facade_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void brine_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void low_kick_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void reversal_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void heavy_slam_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 rage_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 mimic_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void beatup_before_turn(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void beatup_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 tailwind_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 trick_room_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 mist_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 wonder_room_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 safe_guard_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 lucky_chant_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 gravity_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 miracle_eye_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 water_sport_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 mud_sport_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 magnet_rise_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 telekinesis_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 heal_block_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 odor_sleuth_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 foresight_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 mind_reader_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 guard_split_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 power_split_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 speed_swap_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 chip_away_on_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 photon_geyser_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 mind_blown_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void stomping_tantrum_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 laser_focus_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 encore_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 encore_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 torment_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 taunt_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 taunt_on_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 disable_on_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 ingrain_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 smackdown_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 smackdown_on_invul_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 roost_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 rototiller_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 thousand_arrow_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void shell_trap_before_turn(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void instruct_on_after_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 instruct_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 throat_chop_on_effect_cb(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 throat_chop_on_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 perish_song_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 perish_song_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void perish_song_on_after_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 destiny_bond_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 grudge_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 skydrop_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void skydrop_on_damage(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 attract_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 bide_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void bide_on_after_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 helping_hand_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 natures_madness_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 purify_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 gear_up_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 strength_sap_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 sparkling_aria_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 fakeout_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 shore_up_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 infestation_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void false_swipe_on_damage(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 geomancy_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 powder_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 venom_drench_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void water_shuriken_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 flower_shield_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 flower_shield_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 topsy_turvy_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void fell_stinger_after_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void fusion_flare_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void fusion_bolt_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 heat_crash_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void final_gambit_on_damage(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void final_gambit_on_after_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 quick_guard_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void echoed_voice_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void fury_cutter_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void electro_ball_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 synchonoise_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 storm_throw_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 rage_powder_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void venoshock_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void crush_grip_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 captivate_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void avalanche_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 aqua_ring_effect_cb(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 last_resort_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 psycho_shift_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void trump_card_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void assurance_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void payback_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 stockpile_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void stockpile_on_after_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 stockpile_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void spit_up_on_base_power_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 spit_up_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 swallow_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 accupressure_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void gyro_ball_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void wake_up_slap_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 wake_up_slap_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 sky_uppercut_on_invulnerable_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 aromatherapy_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 dive_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void whirlpool_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 whirlpool_on_tryhit_invul(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 refresh_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 imprison_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 endeavor_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void endeavor_on_dmg(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void smelling_salts_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 smelling_salts_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 psych_up_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 dream_eater_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 dig_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void magnitude_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void earthquake_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void frustration_on_damage(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void return_on_damage(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 magnitude_on_tryhit_invul(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 pain_split_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 heal_bell_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 belly_drum_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 spite_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void flail_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 curse_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 snore_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 nightmare_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 tri_attack_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 skull_bash_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 haze_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 mean_look_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void dragon_rage_on_dmg(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 blizzard_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 synthesis_before_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 growth_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 ancient_power_on_modify_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void twister_on_damage(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void triple_kick_on_base_power(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 leech_seed_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 focus_energy_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void focus_punch_before_turn(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void beak_blast_before_turn(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 heart_swap_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 pollen_puff_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 autotomize_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 heal_pulse_on_tryhit_move(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 self_destruct_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 after_you_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 quash_on_tryhit(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void pursuit_on_basepower(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern void pursuit_on_before_turn(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 role_play_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 skill_swap_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 gastro_acid_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 worry_seed_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 dragon_tail_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 volt_switch_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 parting_shot_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 memento_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 lunar_dance_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 block_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 fairy_lock_on_effect(u8 user, u8 src, u16 move, struct anonymous_callback* acb);
extern u8 wrap_partially_trapped_effect_cb(u8 user, u8 src, u16 move, struct anonymous_callback* acb);


/* Move Animation scripts */
extern const u8* PoundAnimation;
extern const u8* KaratechopAnimation;
extern const u8* DoubleSlapAnimation;
extern const u8* CometpunchAnimation;
extern const u8* MegapunchAnimation;
extern const u8* FirepunchAnimation;
extern const u8* IcepunchAnimation;
extern const u8* ThunderpunchAnimation;
extern const u8* VicegripAnimation;
extern const u8* GuillotineAnimation;
extern const u8* RazorwindWhipUpAnimation;
extern const u8* RazorwindAnimation;
extern const u8* SwordsDanceAnimation;
extern const u8* CutAnimation;
extern const u8* GustAnimation;
extern const u8* WingAttackAnimation;
extern const u8* WhirlwindAnimation;
extern const u8* FlyWindUpAnimation;
extern const u8* FlyAnimation;
extern const u8* BindAnimation;
extern const u8* SlamAnimation;
extern const u8* VineWhipAnimation;
extern const u8* StompAnimation;
extern const u8* DoubleKickAnimation;
extern const u8* MegaKickAnimation;
extern const u8* JumpKickAnimation;
extern const u8* RollingKickAnimation;
extern const u8* SandAttackAnimation;
extern const u8* HeadbuttAnimation;
extern const u8* HornAttackAnimation;
extern const u8* FuryAttackAnimation;
extern const u8* HornDrillAnimation;
extern const u8* TackleAnimation;
extern const u8* BodySlamAnimation;
extern const u8* WrapAnimation;
extern const u8* WrapResidualAnimation;
extern const u8* TakedownAnimation;
extern const u8* ThrashAnimation;
extern const u8* DoubleEdgeAnimation;
extern const u8* TailWhipAnimation;
extern const u8* PoisonStingAnimation;
extern const u8* TwineedleAnimation;
extern const u8* PinMissileAnimation;
extern const u8* LeerAnimation;
extern const u8* BiteAnimation;
extern const u8* GrowlAnimation; // files
extern const u8* RoarAnimation;
extern const u8* SingAnimation;
extern const u8* SupersonicAnimation;
extern const u8* SonicBoomAnimation;
extern const u8* DisableAnimation;
extern const u8* AcidAnimation;
extern const u8* EmberAnimation;
extern const u8* FlamethrowerAnimation;
extern const u8* MistAnimation;
extern const u8* WatergunAnimation;
extern const u8* HydroPumpAnimation;
extern const u8* SurfAnimation;
extern const u8* IceBeamAnimation;
extern const u8* BlizzardAnimation;
extern const u8* PsybeamAnimation;
extern const u8* BubbleBeamAnimation;
extern const u8* AuroraBeamAnimation;
extern const u8* HyperBeamAnimation;
extern const u8* PeckAnimation;
extern const u8* DrillPeckAnimation;
extern const u8* SubmissionAnimation;
extern const u8* LowKickAnimation;
extern const u8* CounterAnimation;
extern const u8* SeismicTossAnimation;
extern const u8* StrengthAnimation;
extern const u8* AbsorbAnimation;
extern const u8* MegaDrainAnimation;
extern const u8* LeechSeedAnimation;
extern const u8* GrowthAnimation;
extern const u8* RazorLeafAnimation;
extern const u8* SolarBeamAnimation;
extern const u8* PoisonPowderAnimation;
extern const u8* StunSporeAnimation;
extern const u8* SleepPowderAnimation;
extern const u8* PetalDanceAnimation;
extern const u8* StringShotAnimation;
extern const u8* DragonRageAnimation;
extern const u8* FireSpinAnimation;
extern const u8* ThunderShockAnimation;
extern const u8* ThunderboltAnimation;
extern const u8* ThunderWaveAnimation;
extern const u8* ThunderAnimation;
extern const u8* RockThrowAnimation;
extern const u8* EarthquakeAnimation;
extern const u8* FissureAnimation;
extern const u8* DigAnimation;
extern const u8* ToxicAnimation;
extern const u8* ConfusionAnimation;
extern const u8* PsychicAnimation;
extern const u8* HypnosisAnimation;
extern const u8* MeditateAnimation;
extern const u8* AgilityAnimation;
extern const u8* QuickAttackAnimation;
extern const u8* RageAnimation;
extern const u8* TeleportAnimation;
extern const u8* NightShadeAnimation;
extern const u8* MimicAnimation;
extern const u8* ScreechAnimation;
extern const u8* DoubleTeamAnimation;
extern const u8* RecoverAnimation;
extern const u8* HardenAnimation;
extern const u8* MinimizeAnimation;
extern const u8* SmokescreenAnimation;
extern const u8* ConfuseRayAnimation;
extern const u8* WithdrawAnimation;
extern const u8* DefenseCurlAnimation;
extern const u8* BarrierAnimation;
extern const u8* LightScreenAnimation;
extern const u8* HazeAnimation;
extern const u8* ReflectAnimation;
extern const u8* FocusEnergyAnimation;
extern const u8* BideAnimation;
extern const u8* MetronomeAnimation;
extern const u8* MirrorMoveAnimation;
extern const u8* SelfDestructAnimation;
extern const u8* EggBombAnimation;
extern const u8* LickAnimation;
extern const u8* SmogAnimation;
extern const u8* SludgeAnimation;
extern const u8* BoneClubAnimation;
extern const u8* FireBlastAnimation;
extern const u8* WaterfallAnimation;
extern const u8* ClampAnimation;
extern const u8* SwiftAnimation;
extern const u8* SkullBashAnimation;
extern const u8* SpikeCannonAnimation;
extern const u8* ConstrictAnimation;
extern const u8* AmnesiaAnimation;
extern const u8* KinesisAnimation;
extern const u8* SoftBoiledAnimation;
extern const u8* HighJumpKickAnimation;
extern const u8* GlareAnimation;
extern const u8* DreamEaterAnimation;
extern const u8* PoisonGasAnimation;
extern const u8* BarrageAnimation;
extern const u8* LeechLifeAnimation;
extern const u8* LovelyKissAnimation;
extern const u8* SkyAttackAnimation;
extern const u8* TransformAnimation;
extern const u8* BubbleAnimation;
extern const u8* DizzyPunchAnimation;
extern const u8* SporeAnimation;
extern const u8* FlashAnimation;
extern const u8* PsywaveAnimation;
extern const u8* SplashAnimation;
extern const u8* AcidArmorAnimation;
extern const u8* CrabhammerAnimation;
extern const u8* ExplosionAnimation;
extern const u8* FurySwipesAnimation;
extern const u8* BonemerangAnimation;
extern const u8* RestAnimation;
extern const u8* RockSlideAnimation;
extern const u8* HyperFangAnimation;
extern const u8* SharpenAnimation;
extern const u8* ConversionAnimation;
extern const u8* TriAttackAnimation;
extern const u8* SuperFangAnimation;
extern const u8* SlashAnimation;
extern const u8* SubstituteAnimation;
extern const u8* StruggleAnimation;
extern const u8* SketchAnimation;
extern const u8* TripleKickAnimation;
extern const u8* ThiefAnimation;
extern const u8* SpiderWebAnimation;
extern const u8* MindReaderAnimation;
extern const u8* NightmareAnimation;
extern const u8* FlameWheelAnimation;
extern const u8* SnoreAnimation;
extern const u8* CurseAnimation;
extern const u8* FlailAnimation;
extern const u8* Conversion2Animation;
extern const u8* AeroblastAnimation;
extern const u8* CottonSporeAnimation;
extern const u8* ReversalAnimation;
extern const u8* SpiteAnimation;
extern const u8* PowderSnowAnimation;
extern const u8* ProtectAnimation;
extern const u8* MachPunchAnimation;
extern const u8* ScaryFaceAnimation;
extern const u8* FeintAttackAnimation;
extern const u8* SweetKissAnimation;
extern const u8* BellyDrumAnimation;
extern const u8* SludgeBombAnimation;
extern const u8* MudSlapAnimation;
extern const u8* OctazookaAnimation;
extern const u8* SpikesAnimation;
extern const u8* ZapCannonAnimation;
extern const u8* ForesightAnimation;
extern const u8* DestinyBondAnimation;
extern const u8* PerishSongAnimation;
extern const u8* IcyWindAnimation;
extern const u8* DetectAnimation;
extern const u8* BoneRushAnimation;
extern const u8* LockOnAnimation;
extern const u8* OutrageAnimation;
extern const u8* SandstormAnimation;
extern const u8* GigaDrainAnimation;
extern const u8* EndureAnimation;
extern const u8* CharmAnimation;
extern const u8* RolloutAnimation;
extern const u8* FalseSwipeAnimation;
extern const u8* SwaggerAnimation;
extern const u8* MilkDrinkAnimation;
extern const u8* SparkAnimation;
extern const u8* FuryCutterAnimation;
extern const u8* SteelWingAnimation;
extern const u8* MeanLookAnimation;
extern const u8* AttractAnimation;
extern const u8* SleepTalkAnimation;
extern const u8* HealBellAnimation;
extern const u8* ReturnAnimation;
extern const u8* PresentAnimation;
extern const u8* FrustrationAnimation;
extern const u8* SafeguardAnimation;
extern const u8* PainSplitAnimation;
extern const u8* SacredFireAnimation;
extern const u8* MagnitudeAnimation;
extern const u8* DynamicPunchAnimation;
extern const u8* MegahornAnimation;
extern const u8* DragonBreathAnimation;
extern const u8* BatonPassAnimation;
extern const u8* EncoreAnimation;
extern const u8* PursuitAnimation;
extern const u8* RapidSpinAnimation;
extern const u8* SweetScentAnimation;
extern const u8* IronTailAnimation;
extern const u8* MetalClawAnimation;
extern const u8* VitalThrowAnimation;
extern const u8* MorningSunAnimation;
extern const u8* SynthesisAnimation;
extern const u8* MoonlightAnimation;
extern const u8* HiddenPowerAnimation;
extern const u8* CrossChopAnimation;
extern const u8* TwisterAnimation;
extern const u8* RainDanceAnimation;
extern const u8* SunnyDayAnimation;
extern const u8* CrunchAnimation;
extern const u8* MirrorCoatAnimation;
extern const u8* PsychUpAnimation;
extern const u8* ExtremeSpeedAnimation;
extern const u8* AncientPowerAnimation;
extern const u8* ShadowBallAnimation;
extern const u8* FutureSightAnimation;
extern const u8* RockSmashAnimation;
extern const u8* WhirlpoolAnimation;
extern const u8* BeatUpAnimation;
extern const u8* FakeOutAnimation;
extern const u8* UpRoarAnimation;
extern const u8* StockpileAnimation;
extern const u8* SpitUpAnimation;
extern const u8* SwallowAnimation;
extern const u8* HeatWaveAnimation;
extern const u8* HailAnimation;
extern const u8* TormentAnimation;
extern const u8* FlatterAnimation;
extern const u8* WillOWispAnimation;
extern const u8* MementoAnimation;
extern const u8* FacadeAnimation;
extern const u8* FocusPunchAnimation;
extern const u8* SmellingSaltsAnimation;
extern const u8* FollowMeAnimation;
extern const u8* NaturePowerAnimation;
extern const u8* ChargeAnimation;
extern const u8* TauntAnimation;
extern const u8* HelpingHandAnimation;
extern const u8* TrickAnimation;
extern const u8* RolePlayAnimation;
extern const u8* WishAnimation;
extern const u8* AssistAnimation;
extern const u8* IngrainAnimation;
extern const u8* SuperpowerAnimation;
extern const u8* MagicCoatAnimation;
extern const u8* RecycleAnimation;
extern const u8* RevengeAnimation;
extern const u8* BrickBreakAnimation;
extern const u8* YawnAnimation;
extern const u8* KnockOffAnimation;
extern const u8* EndeavorAnimation;
extern const u8* EruptionAnimation;
extern const u8* SkillSwapAnimation;
extern const u8* ImprisonAnimation;
extern const u8* RefreshAnimation;
extern const u8* GrudgeAnimation;
extern const u8* SnatchAnimation;
extern const u8* SecretPowerAnimation;
extern const u8* DiveAnimation;
extern const u8* ArmThrustAnimation;
extern const u8* CamouflageAnimation;
extern const u8* TailGlowAnimation;
extern const u8* LusterPurgeAnimation;
extern const u8* MistBallAnimation;
extern const u8* FeatherDanceAnimation;
extern const u8* TeeterDanceAnimation;
extern const u8* BlazeKickAnimation;
extern const u8* MudSportAnimation;
extern const u8* IceBallAnimation;
extern const u8* NeedleArmAnimation;
extern const u8* SlackOffAnimation;
extern const u8* HyperVoiceAnimation;
extern const u8* PoisonFangAnimation;
extern const u8* CrushClawAnimation;
extern const u8* BlastBurnAnimation;
extern const u8* HydroCannonAnimation;
extern const u8* MeteorMashAnimation;
extern const u8* AstonishAnimation;
extern const u8* WeatherBallAnimation;
extern const u8* AromatherapyAnimation;
extern const u8* FakeTearsAnimation;
extern const u8* AirCutterAnimation;
extern const u8* OverheatAnimation;
extern const u8* OdorSleuthAnimation;
extern const u8* RockTombAnimation;
extern const u8* SilverWindAnimation;
extern const u8* MetalSoundAnimation;
extern const u8* GrassWhistleAnimation;
extern const u8* TickleAnimation;
extern const u8* CosmicPowerAnimation;
extern const u8* WaterSpoutAnimation;
extern const u8* SignalBeamAnimation;
extern const u8* ShadowpunchAnimation;
extern const u8* ExtrasensoryAnimation;
extern const u8* SkyUppercutAnimation;
extern const u8* SandTombAnimation;
extern const u8* SheerColdAnimation;
extern const u8* MuddyWaterAnimation;
extern const u8* BulletSeedAnimation;
extern const u8* AerialAceAnimation;
extern const u8* IcicleSpearAnimation;
extern const u8* IronDefenseAnimation;
extern const u8* BlockAnimation;
extern const u8* HowlAnimation;
extern const u8* DragonClawAnimation;
extern const u8* FrenzyPlantAnimation;
extern const u8* BulkUpAnimation;
extern const u8* BounceAnimation;
extern const u8* MudShotAnimation;
extern const u8* PoisonTailAnimation;
extern const u8* CovetAnimation;
extern const u8* VoltTackleAnimation;
extern const u8* MagicalLeafAnimation;
extern const u8* WaterSportAnimation;
extern const u8* CalmMindAnimation;
extern const u8* LeafBladeAnimation;
extern const u8* DragonDanceAnimation;
extern const u8* RockBlastAnimation;
extern const u8* ShockWaveAnimation;
extern const u8* WaterPulseAnimation;
extern const u8* DoomDesireAnimation;
extern const u8* PsychoBoostAnimation;
extern const u8* RoostAnimation;
extern const u8* GravityAnimation;
extern const u8* MiracleEyeAnimation;
extern const u8* WakeUpSlapAnimation;
extern const u8* HammerArmAnimation;
extern const u8* GyroBallAnimation;
extern const u8* HealingWishAnimation;
extern const u8* BrineAnimation;
extern const u8* NaturalGiftAnimation;
extern const u8* FeintAnimation;
extern const u8* PluckAnimation;
extern const u8* TailwindAnimation;
extern const u8* AcupressureAnimation;
extern const u8* MetalBurstAnimation;
extern const u8* UturnAnimation;
extern const u8* CloseCombatAnimation;
extern const u8* PaybackAnimation;
extern const u8* AssuranceAnimation;
extern const u8* EmbargoAnimation;
extern const u8* FlingAnimation;
extern const u8* PsychoShiftAnimation;
extern const u8* TrumpCardAnimation;
extern const u8* HealBlockAnimation;
extern const u8* WringOutAnimation;
extern const u8* PowerTrickAnimation;
extern const u8* GastroAcidAnimation;
extern const u8* LuckyChantAnimation;
extern const u8* MeFirstAnimation;
extern const u8* CopycatAnimation;
extern const u8* PowerSwapAnimation;
extern const u8* GuardSwapAnimation;
extern const u8* PunishmentAnimation;
extern const u8* LastResortAnimation;
extern const u8* WorrySeedAnimation;
extern const u8* SuckerPunchAnimation;
extern const u8* ToxicSpikesAnimation;
extern const u8* AquaRingAnimation;
extern const u8* MagnetRiseAnimation;
extern const u8* FlareBlitzAnimation;
extern const u8* ForcePalmAnimation;
extern const u8* AuraSphereAnimation;
extern const u8* RockPolishAnimation;
extern const u8* PoisonJabAnimation;
extern const u8* DarkPulseAnimation;
extern const u8* NightShadeAnimation;
extern const u8* AquaTailAnimation;
extern const u8* SeedBombAnimation;
extern const u8* AirSlashAnimation;
extern const u8* XScissorAnimation;
extern const u8* BugBuzzAnimation;
extern const u8* DragonPulseAnimation;
extern const u8* DragonRushAnimation;
extern const u8* PowerGemAnimation;
extern const u8* DrainPunchAnimation;
extern const u8* VacuumWaveAnimation;
extern const u8* FocusBlastAnimation;
extern const u8* EnergyBallAnimation;
extern const u8* BraveBirdAnimation;
extern const u8* EarthPowerAnimation;
extern const u8* SwitcherooAnimation;
extern const u8* GigaImpactAnimation;
extern const u8* NastyPlotAnimation;
extern const u8* BulletPunchAnimation;
extern const u8* AvalancheAnimation;
extern const u8* IceShardAnimation;
extern const u8* ShadowClawAnimation;
extern const u8* ThunderFangAnimation;
extern const u8* IceFangAnimation;
extern const u8* FireFangAnimation;
extern const u8* ShadowSneakAnimation;
extern const u8* MudBombAnimation;
extern const u8* PsychoCutAnimation;
extern const u8* ZenHeadbuttAnimation;
extern const u8* MirrorShotAnimation;
extern const u8* FlashCannonAnimation;
extern const u8* RockClimbAnimation;
extern const u8* DefogAnimation;
extern const u8* TrickRoomAnimation;
extern const u8* DracoMeteorAnimation;
extern const u8* DischargeAnimation;
extern const u8* LavaPlumeAnimation;
extern const u8* LeafStormAnimation;
extern const u8* PowerWhipAnimation;
extern const u8* RockWreckerAnimation;
extern const u8* CrossPoisonAnimation;
extern const u8* GunkShotAnimation;
extern const u8* IronHeadAnimation;
extern const u8* MagnetBombAnimation;
extern const u8* StoneEdgeAnimation;
extern const u8* CaptivateAnimation;
extern const u8* StealthRockAnimation;
extern const u8* GrassKnotAnimation;
extern const u8* BugBiteAnimation;
extern const u8* ChargeBeamAnimation;
extern const u8* WoodHammerAnimation;
extern const u8* AquaJetAnimation;
extern const u8* AttackOrderAnimation;
extern const u8* DefendOrderAnimation;
extern const u8* HealOrderAnimation;
extern const u8* HeadSmashAnimation;
extern const u8* DoubleHitAnimation;
extern const u8* MagmaStormAnimation;
extern const u8* DarkVoidAnimation;
extern const u8* OminousWindAnimation;
extern const u8* HoneClawsAnimation;
extern const u8* WideGuardAnimation;
extern const u8* GuardSplitAnimation;
extern const u8* PowerSplitAnimation;
extern const u8* PsyshockAnimation;
extern const u8* VenoShockAnimation;
extern const u8* AutomizeAnimation;
extern const u8* RagePowderAnimation;
extern const u8* TelekinesisAnimation;
extern const u8* MagicRoomAnimation;
extern const u8* SmackDownAnimation;
extern const u8* StormThrowAnimation;
extern const u8* FlameBurstAnimation;
extern const u8* SludgeWaveAnimation;
extern const u8* QuiverDnaceAnimation;
extern const u8* HeavySlamAnimation;
extern const u8* SynchronoiseAnimation;
extern const u8* ElectroBallAnimation;
extern const u8* SoakAnimation;
extern const u8* FlameChargeAnimation;
extern const u8* FlameChargeCoilAnimation;
extern const u8* LowSweepAnimation;
extern const u8* AcidSprayAnimation;
extern const u8* FoulPlayAnimation;
extern const u8* SimpleBeamAnimation;
extern const u8* EntrainmentAnimation;
extern const u8* AfterYouAnimation;
extern const u8* RoundAnimation;
extern const u8* EchoedVoiceAnimation;
extern const u8* ChipAwayAnimation;
extern const u8* ClearSmogAnimation;
extern const u8* StoredPowerAnimation;
extern const u8* QuickGuardAnimation;
extern const u8* ScaldAnimation;
extern const u8* ShellSmashAnimation;
extern const u8* HealPulseAnimation;
extern const u8* HexAnimation;
extern const u8* SkyDropAnimation;
extern const u8* CircleThrowAnimation;
extern const u8* IncinerateAnimation;
extern const u8* QuashAnimation;
extern const u8* AcrobaticsAnimation;
extern const u8* ReflectTypeAnimation;
extern const u8* RetaliateAnimation;
extern const u8* FinalGambitAnimation;
extern const u8* BestowAnimation;
extern const u8* InfernoAnimation;
extern const u8* VoltSwitchAnimation;
extern const u8* StruggleBugAnimation;
extern const u8* FrostBeathAnimation;
extern const u8* DragonTailAnimation;
extern const u8* WorkUpAnimation;
extern const u8* ElectrowebAnimation;
extern const u8* WildChargeAnimation;
extern const u8* DrillRunAnimation;
extern const u8* DualChopAnimation;
extern const u8* HornLeechAnimation;
extern const u8* SacredSwordAnimation;
extern const u8* RazorShellAnimation;
extern const u8* LeafTornadoAnimation;
extern const u8* SteamrollerAnimation;
extern const u8* CottonGuardAnimation;
extern const u8* NightDazeAnimation;
extern const u8* PsystrikeAnimation;
extern const u8* TailSlapAnimation;
extern const u8* HurricaneAnimation;
extern const u8* HeadChargeAnimation;
extern const u8* FieryDanceAnimation;
extern const u8* IcicleCrashAnimation;
extern const u8* FlyingPressAnimation;
extern const u8* BlechAnimation;
extern const u8* RototillerAnimation;
extern const u8* StickyWebAnimation;
extern const u8* FellStingerAnimation;
extern const u8* PhantomHitAnimation;
extern const u8* NobleRoarAnimation;
extern const u8* IonDelugeAnimation;
extern const u8* PetalBlizzardAnimation;
extern const u8* FreezeDryAnimation;
extern const u8* DisarmingVoiceAnimation;
extern const u8* PartingShotAnimation;
extern const u8* TopsyTurvyAnimation;
extern const u8* DrainingKissAnimation;
extern const u8* GrassyTerrainAnimation;
extern const u8* MistyTerrainAnimation;
extern const u8* PlayRoughAnimation;
extern const u8* FairyWindAnimation;
extern const u8* MoonblastAnimation;
extern const u8* BoomburstAnimation;
extern const u8* FairyLockAnimation;
extern const u8* KingsShieldAnimation;
extern const u8* PlayNiceAnimation;
extern const u8* SpikyShieldAnimation;
extern const u8* AromaticMistAnimation;
extern const u8* EerieImpulseAnimation;
extern const u8* VenomDrenchAnimation;
extern const u8* PowderAnimation;
extern const u8* MagneticFluxAnimation;
extern const u8* ElectricTerrainAnimation;
extern const u8* DazzlingGleamAnimation;
extern const u8* BabyDollEyesAnimation;
extern const u8* NuzzleAnimation;
extern const u8* HoldBackAnimation;
extern const u8* InfestationAnimation;
extern const u8* PowerUpPunchAnimation;
extern const u8* ShoreUpAnimation;
extern const u8* HighHorsePowerAnimation;
extern const u8* StrengthSapAnimation;
extern const u8* SpotlightAnimation;
extern const u8* ToxicThreadAnimation;
extern const u8* LaserFocusAnimation;
extern const u8* ThroatChopAnimation;
extern const u8* AnchorShotAnimation;
extern const u8* PsychicTerrainAnimation;
extern const u8* LungeAnimation;
extern const u8* PowerTripAnimation;
extern const u8* BurnUpAnimation;
extern const u8* TropKickAnimation;
extern const u8* DragonHammerAnimation;
extern const u8* BrutalSwingAnimation;
extern const u8* ShellTrapAnimation;
extern const u8* PsychicFangsAnimation;
extern const u8* StompingTantrumAnimation;
extern const u8* AccelerockAnimation;
extern const u8* LiquidationAnimation;
extern const u8* TearfulLookAnimation;
extern const u8* ZingZapAnimation;











extern const u8* ShadowpunchAnimation;
extern const u8* WatergunAnimation;
extern const u8* FireworkAnimation;

/* User stats */
extern struct move_procs user_lower_atk_1;
extern struct move_procs user_lower_def_1;
extern struct move_procs user_lower_spAtk_1;
extern struct move_procs user_lower_spDef_1;
extern struct move_procs user_lower_spd_1;
extern struct move_procs user_lower_acc_1;
extern struct move_procs dec_user_atk_def_procs;
extern struct move_procs user_lower_atk_2;
extern struct move_procs user_lower_def_2;
extern struct move_procs user_lower_spAtk_2;
extern struct move_procs user_lower_spDef_2;
extern struct move_procs user_lower_spd_2;
extern struct move_procs user_lower_acc_2;

extern struct move_procs user_raise_atk_1;
extern struct move_procs user_raise_def_1;
extern struct move_procs user_raise_spAtk_1;
extern struct move_procs user_raise_spDef_1;
extern struct move_procs user_raise_spd_1;
extern struct move_procs user_raise_acc_1;
extern struct move_procs user_raise_evn_1;
extern struct move_procs inc_user_spa_3_procs;
extern struct move_procs user_raise_atk_2;
extern struct move_procs user_raise_def_2;
extern struct move_procs user_raise_spAtk_2;
extern struct move_procs user_raise_spDef_2;
extern struct move_procs user_raise_spd_2;
extern struct move_procs user_raise_acc_2;
extern struct move_procs raise_user_Def_SpD;
extern struct move_procs raise_user_Atk_Acc;
extern struct move_procs raise_user_Atk_Def_Acc;
extern struct move_procs raise_user_SpD_SpA_Spd;
extern struct move_procs raise_user_SpA_Atk;
extern struct move_procs raise_user_SpA_50;


/* Target stats */
extern struct move_procs target_lower_atk_1;
extern struct move_procs target_lower_def_1;
extern struct move_procs target_lower_spAtk_1;
extern struct move_procs target_lower_spDef_1;
extern struct move_procs target_lower_spd_1;
extern struct move_procs target_lower_acc_1;
extern struct move_procs dec_SpD_50_procs;
extern struct move_procs target_lower_atk_2;
extern struct move_procs target_lower_def_2;
extern struct move_procs target_lower_def_50_procs;
extern struct move_procs target_lower_spAtk_2;
extern struct move_procs target_lower_spDef_2;
extern struct move_procs target_lower_spd_2;
extern struct move_procs target_lower_acc_2;
extern struct move_procs target_lower_evn_2;
extern struct move_procs dec_SpA_50_procs;
extern struct move_procs low_targ_atk_def;
extern struct move_procs low_tar_acc_30;
extern struct move_procs low_tar_evn_1;
extern struct move_procs low_tar_SpD_30_2;
extern struct move_procs low_tar_acc_40;
extern struct move_procs low_target_atk_SpA;
extern struct move_procs low_target_atk_10;


extern struct move_procs target_raise_atk_1;
extern struct move_procs target_raise_def_1;
extern struct move_procs target_raise_spAtk_1;
extern struct move_procs target_raise_spDef_1;
extern struct move_procs target_raise_spd_1;
extern struct move_procs target_raise_acc_1;

extern struct move_procs target_raise_atk_2;
extern struct move_procs target_raise_def_2;
extern struct move_procs target_raise_spAtk_2;
extern struct move_procs target_raise_spDef_2;
extern struct move_procs target_raise_spd_2;
extern struct move_procs target_raise_acc_2;
extern struct move_procs target_raise_Atk_spAtk_1;
extern struct move_procs target_lower_spe_1_10;

/* Move Specific procs */
extern struct move_procs poison_20_procs;
extern struct move_procs poison_30_procs;
extern struct move_procs poison_40_procs;
extern struct move_procs poison_100_procs;
extern struct move_procs toxic_procs;
extern struct move_procs supersonic_procs;
extern struct move_procs burn_10_procs;
extern struct move_procs freeze_10_procs;
extern struct move_procs confuse_10_procs;
extern struct move_procs confuse_20_procs;
extern struct move_procs confuse_30_procs;
extern struct move_procs confuse_100_procs;
extern struct move_procs paralyze_10_procs;
extern struct move_procs paralyze_30_procs;
extern struct move_procs shell_smash_procs;
extern struct move_procs dragon_ascent_procs;
extern struct move_procs shift_gear_procs;
extern struct move_procs paralyze_100_procs;
extern struct move_procs bubble_beam_procs;
extern struct move_procs aurora_beam_procs;
extern struct move_procs shadow_ball_procs;
extern struct move_procs psychic_procs;
extern struct move_procs target_lower_acc_1_chance_50;
extern struct move_procs sing_procs;
extern struct move_procs rest_procs;
extern struct move_procs target_raise_atk_2_confuse;
extern struct move_procs user_raise_atk_1_10;
extern struct move_procs target_burn_50;
extern struct move_procs target_lower_def_1_30;
extern struct move_procs user_raise_def_1_10;
extern struct move_procs poison_10_procs;
extern struct move_procs target_lower_def_20_procs;
extern struct move_procs ancient_power_procs;
extern struct move_procs burn_100_procs;
extern struct move_procs burn_30_procs;
extern struct move_procs flatter_procs;
extern struct move_procs bad_poison_50_procs;
extern struct move_procs raise_user_atk_20;
extern struct move_procs low_tar_Acc;
extern struct move_procs target_lower_spDef_1_10;
extern struct move_procs dragon_dance_procs;
extern struct move_procs bulk_up_procs;
extern struct move_procs user_raise_spAtk_spDef_1;
extern struct move_procs user_lower_def_spDef_1;
extern struct move_procs geomancy_procs;
extern struct move_procs venom_drench;
extern struct move_procs bug_buzz_procs;
extern struct move_procs charge_beam_procs;
extern struct move_procs focus_energy_proc;
extern struct move_procs focus_energy_proc;
extern struct move_procs low_tar_spAtk_30;
extern struct move_procs v_create;
extern struct move_procs toxic_thread;

#endif /* MOVE_DATA_H_ */
